/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import Share.User;
import Share.MD5Pwd;
import ComunicacaoCliente.ComCliente;
import javax.swing.ButtonGroup;
import LogicaNegocioCliente.ReaderThread;
import LogicaNegocioCliente.Language;
import LogicaNegocioCliente.musica_fundo;
import UserInterface.UIWelcomeScreen;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;

 /**
 * Interface de configurações da aplicação, aonde o utilizador posse aceder às funções
 * de mudança de palavra passe, e-mail, assim como o avatar e ainda tratamento de som 
 * @author Andre, Luciano
 */
public class UIConfiguracoes extends javax.swing.JFrame {

    User player;
    public static UIWelcomeScreen welcomeScreen;
    public static musica_fundo musica;
    public String Lang = Language.getInstance().GetLanguage();
    
    /**
     * Cria a instancia da classe UIConfigurações
     */
    public UIConfiguracoes() {
        initComponents();
        setLocationRelativeTo(null);
        groupButton();
        ErrorLabel.setText("");
        xNewPassword.setVisible(false);
        xOldPassword.setVisible(false);
        xNewEmail.setVisible(false);
        xOldEmail.setVisible(false);
    
    }
    
  /*  public void UpdateLanguage(){
        Lang=Language.getInstance().GetLanguage();
        this.UsernameLabel.setText(java.util.ResourceBundle.getBundle(Lang).getString("UsernameLabel"));
        this.PasswordLabel.setText(java.util.ResourceBundle.getBundle(Lang).getString("PasswordLabel"));
        this.CancelButton.setText(java.util.ResourceBundle.getBundle(Lang).getString("CancelButton"));
        this.ConfimPasswordLabel.setText(java.util.ResourceBundle.getBundle(Lang).getString("ConfirmPasswordLabel"));
        this.ConfirmButton.setText(java.util.ResourceBundle.getBundle(Lang).getString("ConfirmButton"));
        this.ConfirmEmailLabel.setText(java.util.ResourceBundle.getBundle(Lang).getString("ConfirmEmailLabel"));
        this.RegisterUserLabel.setText(java.util.ResourceBundle.getBundle(Lang).getString("RegisterUserLabel"));
    }*/
    
     /**
     * Cria a instancia da classe UIConfigurações
     * @param Jogador do tipo user
     */
    
     public UIConfiguracoes(User Jogador) {
        initComponents();
        groupButton();
        setLocationRelativeTo(null);
        player=Jogador;
        xNewPassword.setVisible(false);
        xOldPassword.setVisible(false);
        xNewEmail.setVisible(false);
        xOldEmail.setVisible(false);
        jPanel1.setOpaque(false);
        jPanel2.setOpaque(false);
        jPanel4.setOpaque(false);
    }
     /*
      * Set genérico
      */
    public void SetLabel(String text){
         this.ErrorLabel.setText(text);
    }
     /*
      * Set genérico
      */
    public void SetConButton(){
         this.SaveButton.setEnabled(true);
    }
     /*
      * Set genérico
      */
    public void groupButton( ) {

        ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(rbavatar1);
        bg1.add(rbavatar2);
        bg1.add(rbavatar3);
        bg1.add(rbavatar4);
        bg1.add(rbavatar5);
        bg1.add(rbavatar6);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ErrorLabel = new javax.swing.JLabel();
        OptionsLabel = new javax.swing.JLabel();
        ImageSettingsLabel = new javax.swing.JLabel();
        SoundEffectsLabel = new javax.swing.JLabel();
        MusicVolumeLabel = new javax.swing.JLabel();
        MusicVolumeSlider = new javax.swing.JSlider();
        AccountSettingsLabel1 = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        avatar6 = new javax.swing.JLabel();
        rbavatar6 = new javax.swing.JRadioButton();
        avatar5 = new javax.swing.JLabel();
        rbavatar5 = new javax.swing.JRadioButton();
        rbavatar4 = new javax.swing.JRadioButton();
        avatar4 = new javax.swing.JLabel();
        rbavatar1 = new javax.swing.JRadioButton();
        avatar1 = new javax.swing.JLabel();
        avatar2 = new javax.swing.JLabel();
        rbavatar2 = new javax.swing.JRadioButton();
        rbavatar3 = new javax.swing.JRadioButton();
        avatar3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        xOldPassword = new javax.swing.JLabel();
        NewPasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        ConfirmaPasswordLabel = new javax.swing.JLabel();
        NewPasswordLabel = new javax.swing.JLabel();
        xNewPassword = new javax.swing.JLabel();
        OldPasswordLabel = new javax.swing.JLabel();
        OldPasswordField = new javax.swing.JPasswordField();
        ChangePasswordLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        xOldEmail = new javax.swing.JLabel();
        ConfirmaPasswordLabel2 = new javax.swing.JLabel();
        NewPasswordLabel2 = new javax.swing.JLabel();
        xNewEmail = new javax.swing.JLabel();
        OldPasswordLabel2 = new javax.swing.JLabel();
        ChangePasswordLabel2 = new javax.swing.JLabel();
        OldEmailField = new javax.swing.JTextField();
        NewEmailField = new javax.swing.JTextField();
        ConfirmEmailField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 252, 20));

        OptionsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        OptionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OptionsLabel.setText("Opções");
        getContentPane().add(OptionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 11, 276, -1));

        ImageSettingsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ImageSettingsLabel.setText("Image Settings");
        getContentPane().add(ImageSettingsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, -1, -1));

        SoundEffectsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SoundEffectsLabel.setText("Efeitos Sonoros");
        getContentPane().add(SoundEffectsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 77, -1, -1));

        MusicVolumeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MusicVolumeLabel.setText("Volume Música:");
        getContentPane().add(MusicVolumeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 125, -1, 20));

        MusicVolumeSlider.setMaximum(0);
        MusicVolumeSlider.setMinimum(-40);
        MusicVolumeSlider.setValue(-20);
        MusicVolumeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MusicVolumeSliderStateChanged(evt);
            }
        });
        getContentPane().add(MusicVolumeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 144, -1));

        AccountSettingsLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AccountSettingsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccountSettingsLabel1.setText("Configurações Conta");
        getContentPane().add(AccountSettingsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 77, 272, -1));

        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 140, 50));

        SaveButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SaveButton.setText("Guardar");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 150, 50));

        avatar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/min_avatar6.png"))); // NOI18N

        avatar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/min_avatar5.png"))); // NOI18N

        avatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/min_avatar4.png"))); // NOI18N

        avatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/min_avatar1.png"))); // NOI18N

        avatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/min_avatar2.png"))); // NOI18N

        avatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/min_avatar3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(avatar4)
                        .addGap(18, 18, 18)
                        .addComponent(avatar5)
                        .addGap(18, 18, 18)
                        .addComponent(avatar6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(rbavatar1))
                            .addComponent(avatar1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avatar2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(rbavatar2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(rbavatar3))
                            .addComponent(avatar3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(rbavatar4)
                        .addGap(49, 49, 49)
                        .addComponent(rbavatar5)
                        .addGap(47, 47, 47)
                        .addComponent(rbavatar6))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(avatar2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(avatar3))
                    .addComponent(avatar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbavatar1)
                    .addComponent(rbavatar2)
                    .addComponent(rbavatar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar6)
                    .addComponent(avatar5)
                    .addComponent(avatar4))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbavatar4)
                    .addComponent(rbavatar5)
                    .addComponent(rbavatar6)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        xOldPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redcross.png"))); // NOI18N

        ConfirmaPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConfirmaPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ConfirmaPasswordLabel.setText("Confirmar Password:");

        NewPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NewPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewPasswordLabel.setText("Nova Password:");

        xNewPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redcross.png"))); // NOI18N

        OldPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OldPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        OldPasswordLabel.setText("Password Antiga:");

        ChangePasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChangePasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChangePasswordLabel.setText("Alteração Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OldPasswordLabel)
                    .addComponent(NewPasswordLabel)
                    .addComponent(ConfirmaPasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OldPasswordField)
                    .addComponent(NewPasswordField)
                    .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xNewPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(xOldPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(ChangePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ChangePasswordLabel)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(OldPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(xOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(xNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NewPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmaPasswordLabel))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 135, -1, -1));

        xOldEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redcross.png"))); // NOI18N

        ConfirmaPasswordLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConfirmaPasswordLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ConfirmaPasswordLabel2.setText("Confirmar Novo Email:");

        NewPasswordLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NewPasswordLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewPasswordLabel2.setText("Novo Email:");

        xNewEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redcross.png"))); // NOI18N

        OldPasswordLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OldPasswordLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        OldPasswordLabel2.setText("Email Antigo:");

        ChangePasswordLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChangePasswordLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChangePasswordLabel2.setText("Alterar Email");

        NewEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewEmailFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmaPasswordLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewPasswordLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OldPasswordLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewEmailField)
                    .addComponent(OldEmailField)
                    .addComponent(ConfirmEmailField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xOldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(xNewEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(ChangePasswordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ChangePasswordLabel2)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OldPasswordLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xOldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OldEmailField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewPasswordLabel2)
                    .addComponent(xNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewEmailField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmaPasswordLabel2)
                    .addComponent(ConfirmEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 303, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        
        
        String username =  player.getUsername();
        String avatar = player.getAvatar();
        char[] Oldpassword = OldPasswordField.getPassword();
        char[] Newpassword = NewPasswordField.getPassword();
        char[] Confirmpassword = ConfirmPasswordField.getPassword();
        this.OldPasswordField.setText("");
        this.NewPasswordField.setText("");
        this.ConfirmPasswordField.setText("");
        String newpass = new String(Newpassword);
        String pConfirm = new String(Confirmpassword);
        String pOld = new String(Oldpassword);
        MD5Pwd enc = new MD5Pwd();
        String passEnc=null; 
        String OpassEnc=null;
        String NewEmail = this.NewEmailField.getText();
        String OldEmail = this.OldEmailField.getText();
        String NewEmailConf = this.ConfirmEmailField.getText();
        
        if (rbavatar1.isSelected()) {
            avatar="avatar1.png";
        } else if (rbavatar2.isSelected()) {
            avatar="avatar2.png";
        } else if (rbavatar3.isSelected()) {
            avatar="avatar3.png";
        } else if (rbavatar4.isSelected()) {
            avatar="avatar4.png";
        } else if (rbavatar5.isSelected()) {
            avatar="avatar5.png";
        } else if (rbavatar6.isSelected()) {
            avatar="avatar6.png";
        }
       
        //SÓ MANDA EMAIL SE FOR PARA ALTERAR CASO CONTRARIO VAI NULL
        //SÓ MANDA PASSWORD SE FOR PARA ALTERAR CASO CONTRARIO VAI NULL
       int flag_pass = 0;
       int flag_email = 0;
       int flag_erro = 0;
        
        
        
        if (!pOld.equals("")){ //existe alteracao da nova pass
            
                if (newpass.equals(pConfirm)){ //novas passwords são iguals

                    //encriptar a nova pass
                    passEnc = enc.encode(username,newpass);
                    OpassEnc = enc.encode(username,pOld);
                    
                    if (!passEnc.equals(player.getPassword())){ //old and new pass foram diferentes ok!
                        
                        if (OpassEnc.equals(player.getPassword())){
                            flag_pass=1; // change password approved
                            flag_erro=1;

                        }else{
                            this.ErrorLabel.setText("Actual Password is Wrong");
                            this.xOldPassword.setVisible(true);
                            this.OldPasswordField.setText("");
                            this.NewPasswordField.setText("");
                            this.ConfirmPasswordField.setText("");
                            flag_erro=1;
                        } 
                         
                    }else{
                        this.ErrorLabel.setText("New and old password are the same!");
                        this.xNewPassword.setVisible(true);
                        this.OldPasswordField.setText("");
                        this.NewPasswordField.setText("");
                        this.ConfirmPasswordField.setText("");
                        flag_erro=1;
                    }

                }else{
                    this.ErrorLabel.setText("New Password doesn't match");
                    this.xNewPassword.setVisible(true);
                    this.OldPasswordField.setText("");
                    this.NewPasswordField.setText("");
                    this.ConfirmPasswordField.setText("");
                    flag_erro=1;
                }
        }else if (!OldEmail.equals("")){ //existe alteracao de email
            
                if (!NewEmail.equals(NewEmailConf)){ //novos emails são iguais
                                        
                    if (!NewEmail.equals(OldEmail)){ //old and new email são foram diferentes ok!
                        
                        if (OldEmail.equals(player.getPassword())){ //old email igual..
                            flag_email=1; // change email approved
                            
                        }else{
                            this.ErrorLabel.setText("Actual Email is wrong!");
                            this.xNewEmail.setVisible(true);
                            this.OldEmailField.setText("");
                            this.NewEmailField.setText("");
                            this.ConfirmEmailField.setText("");
                            flag_erro=1;
                        }
                         
                    }else{
                        this.ErrorLabel.setText("New and old email are the same!");
                        this.xNewEmail.setVisible(true);
                        this.OldEmailField.setText("");
                        this.NewEmailField.setText("");
                        this.ConfirmEmailField.setText("");
                        flag_erro=1;
                    }

                }else{
                    this.ErrorLabel.setText("New email doesn't match!");
                    this.xNewEmail.setVisible(true);
                    this.OldEmailField.setText("");
                    this.NewEmailField.setText("");
                    this.ConfirmEmailField.setText("");
                    flag_erro=1;
                    
                }
        }else  if((pOld.equals("") && OldEmail.equals("") && !avatar.equals(""))){
            try{
            ComCliente com = ComCliente.getInstance();
            com.mudarConfig(player.getUsername(), player.getPassword(), player.getEmail(), avatar, flag_email);
            this.SaveButton.setEnabled(false);
            flag_erro=1;
            }catch (Exception e) {
                System.out.println("Accept failed: 4444");
                System.exit(-1);
        }
        }
        

        if (((flag_pass==1)&& (flag_email==1)&& (flag_erro!=0))){ //alterar pass e email
            try{
                ComCliente com = ComCliente.getInstance();
                com.mudarConfig(username, passEnc, NewEmail, avatar, flag_email);
                this.SaveButton.setEnabled(false);
                flag_email=0;
                flag_pass=0;
            }catch (Exception e) {
                System.out.println("Accept failed: 4444");
                System.exit(-1);
            } 
        }else if (flag_pass==1 && flag_email==0 && (flag_erro!=0)){ //só alterar a pass
            try{
                ComCliente com = ComCliente.getInstance();
                com.mudarConfig(username, passEnc, player.getEmail(), avatar, flag_email);
                this.SaveButton.setEnabled(false);
                flag_pass=0;
            }catch (Exception e) {
                System.out.println("Accept failed: 4444");
                System.exit(-1);
            } 
        }else if (flag_pass==0 && flag_email==1 && flag_erro!=0){ //só alterar a email
            try{
                ComCliente com = ComCliente.getInstance();
                com.mudarConfig(username,null , NewEmail, avatar, flag_email);
                this.SaveButton.setEnabled(false);
                flag_email=0;
            }catch (Exception e) {
                System.out.println("Accept failed: 4444");
                System.exit(-1);
            }
        }else if (flag_erro==0){ //não alterar nem email nem password
                try{
                    ComCliente com = ComCliente.getInstance();
                    com.mudarConfig(username,null , null, avatar, flag_email);
                    this.SaveButton.setEnabled(false);
                }catch (Exception e) {
                    System.out.println("Accept failed: 4444");
                    System.exit(-1);
                }
              }

        flag_erro=0;
       ErrorLabel.setText("");
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void NewEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewEmailFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        ReaderThread.welcomescreen.UIWelcomeSetVisible();
    }//GEN-LAST:event_CancelButtonActionPerformed
    
   

    
    private void MusicVolumeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MusicVolumeSliderStateChanged
        // TODO add your handling code here:
        int volume_opçoes = (int) MusicVolumeSlider.getValue();
        musica.musica_control((float)volume_opçoes);   
        //welcomeScreen.VolumeControlSetValue(volume_opçoes);
    }//GEN-LAST:event_MusicVolumeSliderStateChanged
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        MusicVolumeSliderSetValue();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIConfiguracoes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountSettingsLabel1;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel ChangePasswordLabel;
    private javax.swing.JLabel ChangePasswordLabel2;
    private javax.swing.JTextField ConfirmEmailField;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel ConfirmaPasswordLabel;
    private javax.swing.JLabel ConfirmaPasswordLabel2;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JLabel ImageSettingsLabel;
    private javax.swing.JLabel MusicVolumeLabel;
    private javax.swing.JSlider MusicVolumeSlider;
    private javax.swing.JTextField NewEmailField;
    private javax.swing.JPasswordField NewPasswordField;
    private javax.swing.JLabel NewPasswordLabel;
    private javax.swing.JLabel NewPasswordLabel2;
    private javax.swing.JTextField OldEmailField;
    private javax.swing.JPasswordField OldPasswordField;
    private javax.swing.JLabel OldPasswordLabel;
    private javax.swing.JLabel OldPasswordLabel2;
    private javax.swing.JLabel OptionsLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel SoundEffectsLabel;
    private javax.swing.JLabel avatar1;
    private javax.swing.JLabel avatar2;
    private javax.swing.JLabel avatar3;
    private javax.swing.JLabel avatar4;
    private javax.swing.JLabel avatar5;
    private javax.swing.JLabel avatar6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rbavatar1;
    private javax.swing.JRadioButton rbavatar2;
    private javax.swing.JRadioButton rbavatar3;
    private javax.swing.JRadioButton rbavatar4;
    private javax.swing.JRadioButton rbavatar5;
    private javax.swing.JRadioButton rbavatar6;
    private javax.swing.JLabel xNewEmail;
    private javax.swing.JLabel xNewPassword;
    private javax.swing.JLabel xOldEmail;
    private javax.swing.JLabel xOldPassword;
    // End of variables declaration//GEN-END:variables
}
