/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import ComunicacaoCliente.ComCliente; 
/**
 * Classe da interface do convidar jogador. 
 * @author Luciano
 */

public class UIinvited extends javax.swing.JFrame {
    
  
   
    /**
     * Creates new form UIinvited
     */
    public UIinvited() {
        initComponents();
        setLocationRelativeTo(null);
    }
     /**
     * Creates new form UIinvited
     */
    public UIinvited(String roomname,String roomcreator) {
        initComponents();
        setLocationRelativeTo(null);
        
        NameRoomLabel.setText(roomname);
        
        for (int j=0;j<UIWelcomeScreen.roomsOnlineList.size();j++){
            
            if(UIWelcomeScreen.roomsOnlineList.get(j).getName().equals(roomname)){
                CreatorLabel.setText(UIWelcomeScreen.roomsOnlineList.get(j).getCreator());
                
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WaitingRoomLabel = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        AcceptInviteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CreatorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameRoomLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        WaitingRoomLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        WaitingRoomLabel.setText("Convite de Jogo");

        CancelButton.setText("Recusar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        AcceptInviteButton.setText("Aceitar");
        AcceptInviteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptInviteButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Foi convidado por ");

        CreatorLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CreatorLabel.setText("jLabel2");

        jLabel3.setText("para entar na sala");

        NameRoomLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameRoomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameRoomLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(WaitingRoomLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(CreatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(NameRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AcceptInviteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(WaitingRoomLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreatorLabel)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addComponent(NameRoomLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AcceptInviteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void AcceptInviteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptInviteButtonActionPerformed
         String roomname=NameRoomLabel.getText();
         for (int j=0;j<UIWelcomeScreen.roomsOnlineList.size();j++){
            
            if(UIWelcomeScreen.roomsOnlineList.get(j).getName().equals(roomname)){
                
                if (UIWelcomeScreen.roomsOnlineList.get(j).getCurPlayers()<UIWelcomeScreen.roomsOnlineList.get(j).getNumPlayers()){
                    
                    try {
                        System.out.println("KJDSKJHADSHJKDSAJKHDSAJKHDSAJKHHJKDSA : "+UIWelcomeScreen.player.getUsername());
                        ComCliente com = ComCliente.getInstance();
                        com.joinRoom(roomname, UIWelcomeScreen.player);
                        this.dispose();

                        } catch (Exception ex) {
                            System.out.println("welcomeScreenUI: unable to get Instance in Join");
                        }
                }else{
                    this.dispose();
                }
            }
        }
        
        
    }//GEN-LAST:event_AcceptInviteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIinvited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIinvited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIinvited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIinvited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIinvited().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptInviteButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CreatorLabel;
    private javax.swing.JLabel NameRoomLabel;
    private javax.swing.JLabel WaitingRoomLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
