/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import ComunicacaoCliente.ComCliente; 
/**
 * Classe da interface do convidar jogador. 
 * @author Luciano
 */

public class UIinvite extends javax.swing.JFrame {
    
  
    private String UsernamePlayer; //utilizador a ser convidado
    private String Roomname;
    /**
     * Cria nova instância de UIinvite
     */
    public UIinvite() {
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * Cria nova instância de UIinvite
     */
    UIinvite(String name) {
        initComponents();
        setLocationRelativeTo(null);
        Roomname=name;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WaitingRoomLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserList = new javax.swing.JTable();
        CancelButton = new javax.swing.JButton();
        StartGame1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WaitingRoomLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        WaitingRoomLabel.setText("Convidar Jogador");
        getContentPane().add(WaitingRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, -1, -1));

        jScrollPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseMoved(evt);
            }
        });

        UserList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Jogadores"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(UserList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 70, 159, 188));

        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 289, 117, 54));

        StartGame1.setText("Convidar");
        StartGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGame1ActionPerformed(evt);
            }
        });
        getContentPane().add(StartGame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 289, 117, 54));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void StartGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGame1ActionPerformed
        // TODO add your handling code here:
        if (UserList.getSelectedRow()!=-1){
            try {
                UsernamePlayer=UserList.getValueAt(UserList.getSelectedRow(), 0).toString();
                ComCliente com = ComCliente.getInstance();
                com.invitePlayer(Roomname,UsernamePlayer);
                this.dispose();

            } catch (Exception ex) {
                System.out.println("welcomeScreenUI: unable to get Instance in Join");
            }
        }
        
    }//GEN-LAST:event_StartGame1ActionPerformed

    private void jScrollPane1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseMoved
        // TODO add your handling code here:
        int i;
        int x=0;
        int numPlayers=UIWelcomeScreen.usersOnlineList.size();
       
        //clear jtable clientes
         for(i=0;i<numPlayers;i++){
             UserList.setValueAt("",i,0);
             
         }
         //update UserList
         for(i=0;i<numPlayers;i++){
             
             if (!UIWelcomeScreen.player.getUsername().equals(UIWelcomeScreen.usersOnlineList.get(i).getUsername())){
                 UserList.setValueAt( UIWelcomeScreen.usersOnlineList.get(i).getUsername(),x,0);
                 x++;
             }
             
         }
         
    }//GEN-LAST:event_jScrollPane1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIinvite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIinvite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIinvite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIinvite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIinvite().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton StartGame1;
    private javax.swing.JTable UserList;
    private javax.swing.JLabel WaitingRoomLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
