/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import ComunicacaoCliente.ComCliente; 
/**
 * Classe da interface do convidar jogador. 
 * @author Luciano
 */

public class UIinvited extends javax.swing.JFrame {
    
  
   
    /**
     * Creates new form UIinvited
     */
    public UIinvited() {
        initComponents();
        setLocationRelativeTo(null);
    }
     /**
     * Creates new form UIinvited
     */
    public UIinvited(String roomname,String roomcreator) {
        initComponents();
        setLocationRelativeTo(null);
        
        NameRoomLabel.setText(roomname);
        
        for (int j=0;j<UIWelcomeScreen.roomsOnlineList.size();j++){
            
            if(UIWelcomeScreen.roomsOnlineList.get(j).getName().equals(roomname)){
                CreatorLabel.setText(UIWelcomeScreen.roomsOnlineList.get(j).getCreator());
                
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WaitingRoomLabel = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        AcceptInviteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CreatorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameRoomLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WaitingRoomLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        WaitingRoomLabel.setText("Convite de Jogo");
        getContentPane().add(WaitingRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 29, -1, -1));

        CancelButton.setText("Recusar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 190, 115, 54));

        AcceptInviteButton.setText("Aceitar");
        AcceptInviteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptInviteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AcceptInviteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 190, 117, 54));

        jLabel1.setText("Foi convidado por ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 88, 96, -1));

        CreatorLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CreatorLabel.setText("jLabel2");
        getContentPane().add(CreatorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 88, 110, -1));

        jLabel3.setText("para entar na sala");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 108, -1, -1));

        NameRoomLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameRoomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameRoomLabel.setText("jLabel2");
        getContentPane().add(NameRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 138, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void AcceptInviteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptInviteButtonActionPerformed
         String roomname=NameRoomLabel.getText();
         for (int j=0;j<UIWelcomeScreen.roomsOnlineList.size();j++){
            
            if(UIWelcomeScreen.roomsOnlineList.get(j).getName().equals(roomname)){
                
                if (UIWelcomeScreen.roomsOnlineList.get(j).getCurPlayers()<UIWelcomeScreen.roomsOnlineList.get(j).getNumPlayers()){
                    
                    try {
                        System.out.println("KJDSKJHADSHJKDSAJKHDSAJKHDSAJKHHJKDSA : "+UIWelcomeScreen.player.getUsername());
                        ComCliente com = ComCliente.getInstance();
                        com.joinRoom(roomname, UIWelcomeScreen.player);
                        this.dispose();

                        } catch (Exception ex) {
                            System.out.println("welcomeScreenUI: unable to get Instance in Join");
                        }
                }else{
                    this.dispose();
                }
            }
        }
        
        
    }//GEN-LAST:event_AcceptInviteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIinvited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIinvited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIinvited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIinvited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIinvited().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptInviteButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CreatorLabel;
    private javax.swing.JLabel NameRoomLabel;
    private javax.swing.JLabel WaitingRoomLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
