/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import ComunicacaoCliente.ComCliente;
import LogicaNegocioCliente.ClientStart;
import LogicaNegocioCliente.Language;
import LogicaNegocioCliente.ValidateMail;


/**
 * Interface em que permite ao utilizador recuperar a sua palavra chave inserindo
 * como parâmetro o seu email. Existe também o botão de cancelar que permite voltar 
 * ao UIInitial.
 * @author Kira
 */
public class UIRecoverPass extends javax.swing.JFrame {
    
    public String Lang = Language.getInstance().GetLanguage();

    /**
     * Cria uma instancia da classe RegisterUI.
     */
    public UIRecoverPass() {
        initComponents();
        setLocationRelativeTo(null);
        this.xEmail.setVisible(false);
        this.ErrorLabel.setText("");
    }
     
    /**
     * Este método permite atualizar todos os campos de texto para a linguagem definida 
     * na interface inicial, com o auxílio da classe Language.java.
     * @author João Machado
     * 
     */
        public void UpdateLanguage(){
        Lang=Language.getInstance().GetLanguage();
        this.CancelButton.setText(java.util.ResourceBundle.getBundle(Lang).getString("CancelButton"));
        this.ConfirmButton.setText(java.util.ResourceBundle.getBundle(Lang).getString("ConfirmButton"));
        this.RegisterUserLabel.setText(java.util.ResourceBundle.getBundle(Lang).getString("RecoverPassLabel"));
    }
    
    
    /**
     * Set genérico
     * @param Text texto 
     */
    public void setLabel(String Text){
        this.ErrorLabel.setText(java.util.ResourceBundle.getBundle(Lang).getString("PasswordNew")+Text);
    }
    /**
     * Enable genérico
     *  
     */
    public void EnableButton(){
        this.ConfirmButton.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        EmailField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        RegisterUserLabel = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();
        xEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources/Portugues_pt_PT_EURO"); // NOI18N
        setTitle(bundle.getString("AppTitle")); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConfirmButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ConfirmButton.setText(bundle.getString("ConfirmButton")); // NOI18N
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 286, 171, 55));

        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelButton.setText(bundle.getString("CancelButton")); // NOI18N
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 286, 165, 55));

        EmailField.setAlignmentY(0.0F);
        EmailField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 149, 335, 25));

        EmailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmailLabel.setText("E-Mail:");
        EmailLabel.setAlignmentY(0.0F);
        getContentPane().add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 151, -1, -1));

        RegisterUserLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RegisterUserLabel.setText(bundle.getString("RecoverPassLabel")); // NOI18N
        getContentPane().add(RegisterUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 25, -1, -1));

        ErrorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ErrorLabel.setText("jLabel1");
        getContentPane().add(ErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 210, 335, -1));

        xEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redcross.png"))); // NOI18N
        getContentPane().add(xEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 149, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ClientStart.uiinitial.UISetVisible();

    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        this.ErrorLabel.setText("");
        this.xEmail.setVisible(false);
        this.ConfirmButton.setEnabled(false);
        if (ValidateMail.isValidEmailAddress(EmailField.getText())){
            
            try{
                            ComCliente com = ComCliente.getInstance();
                            com.recoverPass(EmailField.getText());
                            this.ConfirmButton.setEnabled(false);

                        }catch (Exception e) {
                                System.out.println("Accept failed: 4444");
                                System.exit(-1);
                        }   
        }else{
                        this.ErrorLabel.setText(java.util.ResourceBundle.getBundle(Lang).getString("InvalidEmailRecover"));
                        this.xEmail.setVisible(true);
                        this.EmailField.setText("");
                        this.ConfirmButton.setEnabled(true);
        }
        
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIRecoverPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIRecoverPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIRecoverPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIRecoverPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIRecoverPass().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JLabel RegisterUserLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel xEmail;
    // End of variables declaration//GEN-END:variables
}
