/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import ComunicacaoCliente.ComCliente;
import LogicaNegocioCliente.ReaderThread;
import Share.GameRoom;
import Share.User;
import java.util.ArrayList;

/**
 * Classe da interface da sala de espera. 
 * 
 * @author Luciano,Andre
 */
public class UIWaitingRoom extends javax.swing.JFrame {
    public String roomName;
    public static GameRoom roomJoined;
    public static UIinvite uiinvite;
   
    /**
     * Creates new form UIWaitingRoom
     */
    public UIWaitingRoom(GameRoom room) {
        initComponents();
        StartGame.setEnabled(false);
        InvitePlayer.setEnabled(false);
        this.roomJoined = room;
        setLocationRelativeTo(null);
    }
    
    public UIWaitingRoom(){
        initComponents();
        StartGame.setEnabled(false);
        InvitePlayer.setEnabled(false);
        setLocationRelativeTo(null);
    }
    
     public void updateScreen() {
              
         int numRooms   = UIWelcomeScreen.roomsOnlineList.size();
         int statex=1; // 0= criador 1= se nao for
         
         String state;
         
         //clear jtable clientes
         for(int i=0;i<4;i++){
             PlayersList.setValueAt("",i,0);
         }
            //testa se é o criador;
          for (int j=0;j<numRooms;j++){
            
            
            if(UIWelcomeScreen.roomsOnlineList.get(j).getCreator().equals(UIWelcomeScreen.player.getUsername())){
                
                //é o criador...
                InvitePlayer.setEnabled(true);
                if (UIWelcomeScreen.roomsOnlineList.get(j).getCurPlayers()>=2){
                    
                        StartGame.setEnabled(true);
                }else{
                    StartGame.setEnabled(false);
                }
                roomJoined = UIWelcomeScreen.roomsOnlineList.get(j);
                RoomNameLabel.setText(UIWelcomeScreen.roomsOnlineList.get(j).getName());
                PlayersNumberLabel.setText(Integer.toString(UIWelcomeScreen.roomsOnlineList.get(j).getNumPlayers()));
                statex=0;
                ArrayList<User> player= UIWelcomeScreen.roomsOnlineList.get(j).getBroadcast();
                for(int i=0;i<player.size();i++){
                             
                            PlayersList.setValueAt(i+1,i,0);    
                            PlayersList.setValueAt(player.get(i).getUsername(),i,1);
                            
                         }
            }
        }
        
        if (statex!=0){
            
           for (int j=0;j<numRooms;j++){
            
                //n é o criador...
                for (int jj=0;jj<UIWelcomeScreen.roomsOnlineList.get(j).getCurPlayers();jj++){
                        
                     
                    if(UIWelcomeScreen.player.getUsername().equals(UIWelcomeScreen.roomsOnlineList.get(j).getPlayer(jj).getUsername())){
                        
                       
                        roomJoined = UIWelcomeScreen.roomsOnlineList.get(j);
                        ReaderThread.room=roomJoined;
                        RoomNameLabel.setText(UIWelcomeScreen.roomsOnlineList.get(j).getName());
                        PlayersNumberLabel.setText(Integer.toString(UIWelcomeScreen.roomsOnlineList.get(j).getNumPlayers()));
                         ArrayList<User> player= UIWelcomeScreen.roomsOnlineList.get(j).getBroadcast();
                         for(int i=0;i<player.size();i++){
                            PlayersList.setValueAt(i+1,i,0);      
                            PlayersList.setValueAt(player.get(i).getUsername(),i,1);
                            
                         }
                    }
                }
            
            }  
        }
        ReaderThread.room=roomJoined;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WaitingRoomLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PlayersList = new javax.swing.JTable();
        RoomNameLabel = new javax.swing.JLabel();
        PlayersNumberLabel = new javax.swing.JLabel();
        StartGame = new javax.swing.JButton();
        InvitePlayer = new javax.swing.JButton();
        LeaveRoom = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        NumberLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WaitingRoomLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        WaitingRoomLabel.setText("Sala de Espera ");
        getContentPane().add(WaitingRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 32, -1, -1));

        PlayersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Jogadores"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PlayersList.setSelectionBackground(new java.awt.Color(204, 204, 255));
        PlayersList.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(PlayersList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 187, 379, 91));

        RoomNameLabel.setText("_");
        getContentPane().add(RoomNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 104, -1, -1));

        PlayersNumberLabel.setText("_");
        getContentPane().add(PlayersNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 132, -1, -1));

        StartGame.setText("Iniciar Jogo");
        StartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameActionPerformed(evt);
            }
        });
        getContentPane().add(StartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 289, 110, 54));

        InvitePlayer.setText("Convidar Jogador");
        InvitePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvitePlayerActionPerformed(evt);
            }
        });
        getContentPane().add(InvitePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 140, 54));

        LeaveRoom.setText("Sair da Sala");
        LeaveRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveRoomActionPerformed(evt);
            }
        });
        getContentPane().add(LeaveRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 290, 110, 54));

        NameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NameLabel.setText("Nome da Sala:");
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 101, 171, -1));

        NumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NumberLabel.setText("Nº de Jogadores:");
        getContentPane().add(NumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 129, 171, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameActionPerformed
         
        //Iniciar jogo
        
        
        ComCliente com = ComCliente.getInstance();
        try {
            com.StartGame(roomJoined);
            
        } catch (Exception ex) {
            System.out.println("WaitingRoomUI: unable to get instance in Join");
        }
        
    }//GEN-LAST:event_StartGameActionPerformed

    private void InvitePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvitePlayerActionPerformed
        // TODO add your handling code here:
        
        uiinvite = new UIinvite(roomJoined.getName());
        uiinvite.setVisible(true);
    }//GEN-LAST:event_InvitePlayerActionPerformed

    private void LeaveRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveRoomActionPerformed
        
        String roomName = roomJoined.getName();
        
        
        ComCliente com = ComCliente.getInstance();
        try {
            com.leaveRoom(roomName, UIWelcomeScreen.player);
            
        } catch (Exception ex) {
            System.out.println("WaitingRoomUI: unable to get instance in Join");
        }
        
    }//GEN-LAST:event_LeaveRoomActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        updateScreen();
    }//GEN-LAST:event_formMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        updateScreen();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIWaitingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIWaitingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIWaitingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIWaitingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIWaitingRoom().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InvitePlayer;
    private javax.swing.JButton LeaveRoom;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NumberLabel;
    private javax.swing.JTable PlayersList;
    private javax.swing.JLabel PlayersNumberLabel;
    private javax.swing.JLabel RoomNameLabel;
    private javax.swing.JButton StartGame;
    private javax.swing.JLabel WaitingRoomLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
